### ISSUE TITLE
t/bigrat.t may fail

### ISSUE THREAD

**Issue by eserte** [Grinnz/Math-Calc-Parser#2]
On some of my linux smokers (e.g. most debian/stretch configurations) the test suite fails:
```
Use of uninitialized value in string eq at /opt/perl-5.24.4t/lib/site_perl/5.24.4/Math/BigFloat.pm line 3689.

#   Failed test 'Cast to integer'
#   at t/bigrat.t line 32.
#          got: '5/2'
#     expected: '2'
Use of uninitialized value in string eq at /opt/perl-5.24.4t/lib/site_perl/5.24.4/Math/BigFloat.pm line 3689.

#   Failed test 'Cast to integer'
#   at t/bigrat.t line 33.
#          got: '-5/2'
#     expected: '-2'
# Looks like you failed 2 tests of 23.
t/bigrat.t ............. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/23 subtests 
```

**Comment by Grinnz** [comment]
Do you happen to know what version of Math::BigRat that is using?

**Comment by eserte** [comment]
One of them has Math::BigRat 0.260802 installed.

**Comment by Grinnz** [comment]
I can't install that version of Math::BigRat because it overwrote the core version instead of the site version. Lovely. (working on it...)

**Comment by eserte** [comment]
I can confirm that the test suite passes everywhere (except on 5.8.1) with the newest Math::BigRat.

**Comment by Grinnz** [comment]
Hopefully should be resolved by increasing the required versions to enable this functionality/tests to the April 2016 refactor of these modules. Thanks for the report.
